#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { build } = require('esbuild');

const ROOT_DIR = path.join(__dirname, '..');
const SRC_DIR = path.join(ROOT_DIR, 'src');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const WORKER_DIST_DIR = path.join(ROOT_DIR, 'dist-worker');
const GENERATED_DIR = path.join(SRC_DIR, 'generated');
const WORKER_ENTRY = path.join(SRC_DIR, 'worker', 'index.ts');

/**
 * The host rejects a script over 100 KB
 * (`PluginNodeExecutor.validateScriptRequest`). Leave room for the JSON args
 * the host inlines into the same script text.
 */
const MAX_WORKER_SOURCE_LENGTH = 80_000;

/**
 * Mirror of the host's `canExecuteDirectly` check in
 * `electron/plugin-node-executor.ts`. A script that does NOT match this runs in
 * a `vm` sandbox where only fs/path/os can be required — no `tls`, so no IMAP.
 * Matching is therefore a hard requirement, not a nicety: it is what routes us
 * to the spawned Node process.
 */
const HOST_SPAWN_PATH_PATTERN =
  /require\s*\(\s*['"`](?!fs|path|os)[^'"]+['"`]\s*\)|child_process|exec|spawn|eval|Function|process\.exit/;

const buildWorkerBundles = async () => {
  fs.rmSync(WORKER_DIST_DIR, { recursive: true, force: true });
  fs.mkdirSync(WORKER_DIST_DIR, { recursive: true });

  // CommonJS build: what the integration tests require() and drive against a
  // fake IMAP server. Same sources as the embedded copy, so a protocol bug
  // cannot hide behind a build difference.
  await build({
    entryPoints: [WORKER_ENTRY],
    bundle: true,
    outfile: path.join(WORKER_DIST_DIR, 'imap-worker.cjs'),
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    logLevel: 'warning',
  });

  // Minified copy of the same CJS bundle, embedded into plugin.js as a string
  // and handed to executeNodeScript, which evaluates it as a function body.
  // CJS (not IIFE) on purpose: esbuild's IIFE output routes node builtins
  // through a `__require` helper, which erases the literal `require("tls")`
  // that the host's spawn-path check looks for.
  const embedded = await build({
    entryPoints: [WORKER_ENTRY],
    bundle: true,
    write: false,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    minify: true,
    logLevel: 'warning',
  });

  const source = escapeControlChars(embedded.outputFiles[0].text);
  assertWorkerSource(source);

  // The host evaluates the script as the body of an async function with `args`
  // in scope and no module system, so the CommonJS bundle gets a local
  // `module`/`exports` to attach to. Assembled here, once, so the integration
  // test can drive the exact same bytes the plugin ships.
  const hostScript = [
    'const module = { exports: {} };',
    'const exports = module.exports;',
    source,
    'return module.exports.run(args[0]);',
  ].join('\n');

  fs.writeFileSync(path.join(WORKER_DIST_DIR, 'host-script.js'), hostScript);
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(GENERATED_DIR, 'worker-source.ts'),
    [
      '// GENERATED by scripts/build.js — do not edit.',
      '// The bundled IMAP worker, wrapped exactly as executeNodeScript needs it.',
      `export const WORKER_SCRIPT = ${JSON.stringify(hostScript)};`,
      '',
    ].join('\n'),
  );
  console.log(
    `  worker bundle: ${source.length} chars (limit ${MAX_WORKER_SOURCE_LENGTH})`,
  );
};

/**
 * esbuild's printer writes escapes like `\u0001` back out as RAW control
 * characters inside string and regex literals. That is valid JavaScript, but
 * the host runs the script via `spawn(execPath, ['-e', script])` and Node
 * rejects any argv entry containing a NUL byte (ERR_INVALID_ARG_VALUE) — so a
 * raw control character here breaks every call the plugin makes, on every
 * platform, with an error that says nothing about IMAP.
 *
 * Re-escaping is safe on this input: the bundle has no comments, so a control
 * character can only sit inside a string, template or regex literal, and
 * `\uXXXX` means exactly the same thing in all three.
 */
const escapeControlChars = (source) =>
  // eslint-disable-next-line no-control-regex
  source.replace(
    /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,
    (ch) => `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`,
  );

const assertWorkerSource = (source) => {
  if (source.length > MAX_WORKER_SOURCE_LENGTH) {
    throw new Error(
      `Worker bundle is ${source.length} chars, over the ${MAX_WORKER_SOURCE_LENGTH} limit. ` +
        'The host rejects scripts above 100 KB — trim the worker instead of raising this.',
    );
  }
  if (!source.includes('require("tls")')) {
    throw new Error(
      'Worker bundle has no literal require("tls"). IMAP needs a TLS socket, and the ' +
        'literal is also what the host matches on to pick the spawned-process path.',
    );
  }
  // eslint-disable-next-line no-control-regex
  const rawControl = /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.exec(source);
  if (rawControl) {
    throw new Error(
      `Worker bundle still contains a raw control character (U+${rawControl[0]
        .charCodeAt(0)
        .toString(16)
        .padStart(4, '0')}). ` + 'spawn() rejects an argv entry with a NUL byte.',
    );
  }
  if (!HOST_SPAWN_PATH_PATTERN.test(source)) {
    throw new Error(
      'Worker bundle does not match the host pattern that routes a script to the spawned ' +
        'Node process; it would run in the vm sandbox where only fs/path/os exist.',
    );
  }
};

const buildPlugin = async () => {
  fs.rmSync(DIST_DIR, { recursive: true, force: true });
  fs.mkdirSync(DIST_DIR, { recursive: true });

  await build({
    entryPoints: [path.join(SRC_DIR, 'plugin.ts')],
    bundle: true,
    outfile: path.join(DIST_DIR, 'plugin.js'),
    platform: 'browser',
    target: 'es2020',
    format: 'iife',
    minify: true,
    logLevel: 'warning',
  });

  fs.copyFileSync(
    path.join(SRC_DIR, 'manifest.json'),
    path.join(DIST_DIR, 'manifest.json'),
  );
  fs.copyFileSync(path.join(ROOT_DIR, 'icon.svg'), path.join(DIST_DIR, 'icon.svg'));
  fs.copyFileSync(
    path.join(SRC_DIR, 'ui', 'index.html'),
    path.join(DIST_DIR, 'index.html'),
  );
};

const main = async () => {
  console.log('Building imap-inbox...');
  await buildWorkerBundles();
  await buildPlugin();
  console.log('Build complete!');
};

main().catch((err) => {
  console.error('Build failed:', err.message);
  process.exit(1);
});
